### PR TITLE
Create new file and modify eiei.txt

### PR DESCRIPTION
**Pull request by ningnongday**
eiei and kiki

### CODE REVIEW

**Comment by boyscrump** [comment]
eqweqwe

**Comment by Yeenlnwza007** [comment]
how to use this file

**Comment by ningnongday** [comment]
kak

**Comment by Yeenlnwza007** [comment]
just call and use

**Comment by boyscrump** [comment]
82

**Comment by ningnongday** [comment]
Bus 8

**Comment by Yeenlnwza007** [comment]
ok l will plll to master

**Comment by boyscrump** [comment]
pdasdasd

**Comment by boyscrump** [comment]
82

**Comment by boyscrump** [comment]
+kub +kub

**Comment by boyscrump** [comment]
+++++

**Comment by boyscrump** [comment]
++++++#

**Pull request merged**
